### ISSUE TITLE
Provide type alias for default controller

### ISSUE THREAD

**Issue by JosiahParry** [brahmlower/prefixed-api-key#17]
I'd like to be able to make a function that takes a reference to the prefixed api controller as provided by the builder. However, the builder's type (the one as shown in the example in the README) has a type of `PrefixedApiKeyController<OsRng, CoreWrapper<CtVariableCoreWrapper<Sha256VarCore,UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>,OidSha256,>,>` (according to the rust analyzer). 

I am not able to figure out the imports and the like to be able to actually use this type which makes it fairly hard to use in practice. 

To make it easier, I would suggest that a type alias is provided by the crate.

**Comment by brahmlower** [comment]
Hey @JosiahParry thanks for the suggestion! I'll look at adding the type aliases some time this week

**Comment by brahmlower** [comment]
I'll cut a release with these changes later today 👍

**Comment by brahmlower** [comment]
Alrighty @JosiahParry, this change has been released as part of version `0.3.0`. There were a couple other changes that went out in the release, so I'd recommend taking a quick look at the [changelog](https://github.com/brahmlower/prefixed-api-key/blob/main/CHANGELOG.md#030---2024-08-20) just in case 😁 

Thanks again for the feature suggestion! 🙏
